demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from simple import views

urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^simple/', include('simple.urls')),
    url(r'^batching/', include('batching.urls')),
    url(r'^admin/', admin.site.urls),
]

simple/urls.py
from django.conf.urls import url

from simple import views

app_name = 'simple'
urlpatterns = [
    url(r'^$', views.simple, name='input'),
    url(r'^analysis', views.analysis, name='analysis'),
    url(r'^(?P<pk>[0-9]+)/results$', views.ResultView.as_view(), name='results'),
]

simple/models.py
# coding:utf-8
from __future__ import unicode_literals

import json
import urllib2
from urllib import urlencode

from django.contrib import admin
from django.core.validators import MinLengthValidator
from django.db import models

# Create your models here.
from django.utils import timezone
import jieba.posseg as pseg
import re

from simple.algorithm import judge
from simple.algorithm.syntacticAnalysis import SyntacticAnalysis



def wash_data(text):
    text = re.sub('【[^【】]*】', '', text)  # 去除包含在【……】中的内容
    text = re.sub('【[^【?]*?', '', text)  # 去除包含在【……?中的内容
    text = re.sub('【[^【？]*？', '', text)  # 去除包含在【……？中的内容
    text = re.sub('#[^#]*#', '', text)  # 去除包含在#……#中的内容
    text = re.sub('//@[^：]*：', '', text)  # 去除//@……：中的内容
    text = re.sub('//@[^:]*:', '', text)  # 去除//@……: 中的内容
    text = re.sub('@[^ \t]*[ \t]', '', text)  # 去除@后跟部分直到遇到制表符或者空格
    text = re.sub('^[^【】]*】', '', text)  # 若文本中仅有】而没有【，则去除】之前的所有部分
    text = re.sub('《[^《》]*》', '', text)  # 去除包含在《……》中的内容
    text = re.sub('（[^（）]*）', '', text)  # 去除（……）中的内容
    text = re.sub('……', '，', text)  # 将“……”替换为“，”（此处须为完整的中文省略号）
    text = re.sub('[；;]', '，', text)  # 将“；”和“;”替换为“，”
    text = re.sub('\"[^\"]*\"', '', text)  # 去除双引号内的所有内容
    text = re.sub('“[^“”]*”', '', text)  # 去除双引号内的所有内容
    text = re.sub(
        '^(((http|https|ftp)://)?([[a-zA-Z0-9]\-\.])+(\.)([[a-zA-Z0-9]]){2,4}([[a-zA-Z0-9]/+=%&_\.~?\-]*))*$',
        '', text)  # 去除网址
    # text = re.sub('\[[^\[\]]*\]', '', text)  # 去除中括号括起来的部分
    # text = re.sub('(\d)(O|o|〇)(?=\d)', '\\g<1>0', text)  # 替换数字间写错的零成：0
    return text


class Simple(models.Model):
    sentence_text = models.CharField(max_length=200, unique=True, null=False, validators=[MinLengthValidator(1)])
    preprocess_sen = models.CharField(max_length=200, null=True)
    pos_tagging = models.CharField(max_length=200, null=True)
    lexical_tree = models.TextField('lexical tree', null=True)
    request_date = models.DateTimeField('date requested', default=timezone.now)
    request_count = models.PositiveIntegerField('count', default=0)
    pv_word = models.TextField("pv word", null=True)
    pv_modifier_word = models.TextField("pv modifier word", null=True)
    keywords = models.TextField("keywords", null=True)
    emotion = models.IntegerField('emotion', default=-1)

    def __str__(self):
        return self.sentence_text

    def __unicode__(self):
        return u'%s' % self.sentence_text

    def get_washed_text(self, refresh=False):
        """
        获取预处理后的数据
        :param refresh: 如果refresh设置为True，则强制进行依次预处理，再返回结果
        :return: 第一次调用会进行一次预处理，并把结果存入数据库，之后调用将直接从数据库读取结果
        """
        if self.preprocess_sen is None or refresh:
            self.preprocess_sen = wash_data(self.sentence_text)
            self.save()
        print "washed text :%s" % self.preprocess_sen
        return self.preprocess_sen

    def get_seg_json(self, refresh=False):
        """
        获取jieba分词结果的json格式
        :param refresh: 是否强制重新分词，并刷新分词结果
        :return: jieba分词
        """
        if self.pos_tagging is None or refresh:
            words = pseg.cut(self.get_washed_text())
            self.pos_tagging = ''
            for word, flag in words:
                self.pos_tagging += (word + flag[0] + ',')
            self.pos_tagging = self.pos_tagging[:-1]
            self.save()
        return self.pos_tagging

    def get_lexical_tree(self, refresh=False):
        """
        获取词法分析树的数据（调用哈工大云的API）
        :param refresh: 是否强制刷新数据，是则重新调用哈工大云API
        :return: 词法分析树的json格式数据
        """
        if self.lexical_tree is None or len(self.lexical_tree) == 0 or refresh:
            text = self.get_washed_text()
            params = {
                'api_key': 'N5G9s2d6TVoT7mptglCmWagXJqWWKAfBMBlDxJBR',
                'text': text.encode('utf8'), 'format': 'json', 'pattern': 'all'}

            params = urlencode(params)
            url = "http://api.ltp-cloud.com/analysis/?" + params
            result = urllib2.urlopen(url)
            content = result.read().strip()
            content = re.sub('\n', ' ', content.decode('utf8')).encode('utf8')

            self.lexical_tree = content
            self.save()

        print self.lexical_tree
        return self.lexical_tree

    def get_lexical_tree_strip(self):
        content = self.get_lexical_tree()
        content = json.loads(content)[0][0]
        content = json.dumps(content)
        return content

    def syntactic(self):
        """
        call API from algorithm to tell the syntactic of this sentence
        :return: Negative, Declarative or Question
        """

        if self.emotion < 0:
            washed = self.get_washed_text()
            segs = self.get_seg_json()
            ltp = self.get_lexical_tree_strip()
            ltp_list = []
            ltp_list.append(ltp.encode('utf8'))
            washed_list = []
            washed_list.append(washed.encode('utf8'))
            segs_list = []
            segs_list.append(segs.encode('utf8'))
            id_list = []
            id_list.append(self.id)

            # hgd_file 是指经过哈工大预处理后的句子
            # test_numark_file 是指没有处理过的句子
            # test_file 是指分词后句子

            result = judge.test(washed_list, segs_list, ltp_list, id_list)
            if result is None:
                self.emotion = -1
            else:
                self.emotion = result
            self.save()
        if self.emotion == 0:
            return '疑问句'
        if self.emotion == 1:
            return '否定句'
        if self.emotion == 2:
            return '陈述句'
        return self.emotion


class SentenceAdmin(admin.ModelAdmin):
    fieldsets = [
        (None, {'fields': ['sentence_text', 'request_count', 'washed_text', 'seg_json', 'lexical_tree', 'emotion']}),
        ('Date Info.', {'fields': ['request_date']})
    ]
    list_display = ('sentence_text', 'request_date', 'emotion', 'request_count')
    search_fields = ['sentence_text']


admin.site.register(Simple, SentenceAdmin)

simple/views.py
# coding:utf-8

from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.utils import timezone

from django.utils.translation import ugettext as _
from django.views import generic

from simple.models import Simple


def index(request):
    sentence = _("Please Enter A Sentence:")
    return render(request, 'simple/index.html', context={'sentence': sentence})


def simple(request):
    return render(request, 'simple/demo.html')


def analysis(request):
    # get the sentence
    try:
        sentence = request.POST['input']
    except KeyError:
        return render(request, 'simple/index.html')

    print "Sentence: %s" % sentence

    m_sentence, created = Simple.objects.get_or_create(sentence_text=sentence)
    m_sentence.request_count += 1
    m_sentence.request_date = timezone.now()
    m_sentence.save()

    return HttpResponseRedirect(reverse('simple:results', args=(m_sentence.id,)))


class ResultView(generic.DetailView):
    model = Simple
    template_name = 'simple/results.html'

    def get_context_data(self, **kwargs):
        context = super(ResultView, self).get_context_data(**kwargs)
        return context


def feedback(request):
    try:
        sentence = request.POST['input']
    except KeyError:
        return render(request, 'simple/index.html')

simple/templates/simple/demo.html
{% extends "navbar.html" %}
{% load staticfiles %}

{% block title %}单句处理{% endblock %}

{% load staticfiles %}


{% block content %}

    <div class="doc-header">
        <div class="container">
            <h1>单句处理</h1>
            <p>我们帮您进行句子分析</p>
        </div>

        <div id="usageIntroduction" class=" container alert alert-block fade in">
            <h1>使用介绍</h1>
            用户在界面输入一个句子，系统输出：<br>
            <ul>
                <li>句子中的关键词</li>
                <li>句子的语法结构</li>
                <li>句子的语气</li>
            </ul>

            <h2>你们对系统准确性的评判能让我们做的更好!</h2>
            <button id="alertclose" type="button" class="close" onclick="$('#usageIntroduction').alert('close');
          appendText()"><span>试一试</span>
            </button>
        </div>
    </div>
    <!--将后面输入和显示框与上面的导航栏拉开一定差距-->
    <div id="warpper">
        <div class="container" id="doc-input" style="display:none">
            {% include 'simple/search_box.html' %}
        </div>
    </div>
    <script src="{% static 'js/d3.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/parser.js' %}" type="text/javascript"></script>

    <script type="text/javascript" src="{% static 'js/feedback.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/analysis.js' %}"></script>

    <script>//    将输入栏目显示出来   设置了200s的延时
    function appendText() {
        setTimeout(function () {
            $("#doc-input").attr("style", "display:block");
        }, 200);
    }
    </script>


{% endblock %}

simple/templates/simple/index.html
{% extends "navbar.html" %}

{% block title %}简介{% endblock %}

simple/templates/simple/results.html
{% extends "navbar.html" %}

{% load staticfiles %}
{% block title %}{{ object.get_washed_text }}{% endblock %}

{% block content %}

    <link href="{% static 'css/simple_result.css' %}" rel="stylesheet" type="text/css">

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>
    {% else %}{% endif %}


    <div class="jumbotron">

        <!--展示结果-->
        <div class="container" id="analysis-Panel">

            {% include 'simple/search_box.html' %}

            <svg id="parserTree"></svg>

            <div class="panel-collapse" id="show_text"></div>

            <div class="row">
                <div class="col-lg-10">
                    <!--注意下一句的类型-->
                    <p class="bg-primary" id="feedbackText"></p>
                </div>
                <div class="col-lg-2">
                    <div class="btn-group">
                        <button class="btn" id="backBtn">正确</button>
                        <button class="btn dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a id="cQuestion" href="#">疑问句</a></li>
                            <li><a id="cNegatives" href="#">否定句</a></li>
                            <li><a id="cState" href="#">陈述句</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="panel-collapse">
                {{ object.get_lexical_tree }}
            </div>

        </div>
    </div>
{% endblock %}


{% block javascripts %}
    <script src="{% static 'js/d3.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/parser.js' %}" type="text/javascript"></script>

    <script type="text/javascript" src="{% static 'js/feedback.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/analysis.js' %}"></script>
    <script>

        parser({{ object.get_lexical_tree_strip|safe }});
        var $sentence = "{{ object.sentence_text }}";
        var $content = $("#analysis-Panel");

        $content.find("#show_text").append($sentence);
        $content.find("#feedbackText").append('{{ object.syntactic }}');
        if (!$content.is(":visible")) {
            $content.show();
        }

    </script>


    <script>
        /**
         * Created by eligah on 2016/3/30.
         */
        send_feedback = function (id, original, feedback) {
            $.post()
        };
        $(function () {
            $("#cQuestion").bind("click", function () {
                $("#backBtn").replaceWith("<button class=\"btn\" id=\"backBtn\">疑问句</button>")
            });
            $("#cNegatives").bind("click", function () {
                $("#backBtn").replaceWith("<button class=\"btn\" id=\"backBtn\">否定句</button>")
            });
            $("#cState").bind("click", function () {
                $("#backBtn").replaceWith("<button class=\"btn\" id=\"backBtn\">陈述句</button>")
            });
        })


    </script>
{% endblock %}

simple/templates/simple/search_box.html
<form action="{% url 'simple:analysis' %}" method="post">
    {% csrf_token %}
    <div class="row-fluid">
        <div class="col-lg-10">
            <input class="form-control" type="text" name="input" placeholder="请输入想要分析的句子"/>
        </div>
        <div class="col-lg-2">
            <input type="submit" id="analysis" class="btn btn-default" value="分析"/>
        </div>
    </div>
</form>

simple/templates/simple/try.html
{% extends "navbar.html" %}

{% block content %}
    <div id="usageIntroduction" class="alert alert-block fade in">
        <button id="alertclose" type="button" class="close" onclick="$('#usageIntroduction').alert('close');
        ">&times
        </button>
        <h1>使用介绍</h1>
        <p>用户在界面输入一个句子，系统输出：<br>
        <li>句子中的关键词</li>
        <li>句子的语法结构</li>
        <li>句子的语气</li>
        </p>
        <p>你们对系统准确性的评判能让我们做的更好!</p>
    </div>
    <!--<div class="usageIntroduction" style="display: none">-->
    <!--<h1>使用介绍</h1>-->
    <!--<p>用户在界面输入一个句子，系统输出：<br>-->
    <!--<li>句子中的关键词</li>-->
    <!--<li>句子的语法结构</li>-->
    <!--<li>句子的语气</li>-->
    <!--</p>-->
    <!--<p>你们对我们系统准确性的评判能让我们做的更好</p>-->
    <!--<button-->
    <!--</div>-->
    <!--</div>-->
{% endblock %}


<script>
    <!-- js代码 消息提示 ,点击事件 -->
    $('#alertclose').click(function () {
        $('#alerttest').alert('close');
    });
</script>